### ISSUE TITLE
Update bug

### ISSUE THREAD

**Issue by kikswosil** [GeFeC/Flask-todo#4]
Jak kliknąć escape na prompcie przy updacie to prompt się zamyka, a tytuł ustawia sie na pusty. Poza tym prompt otwiera się z pustym tytułem
![update-fail](https://user-images.githubusercontent.com/78105067/205005500-bb35ae4f-1b38-4d37-83cb-7800255f9a99.png)

**Comment by GeFeC** [comment]
Fixnięte
